/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "Color.Neutral.White": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        1,
        1
      ],
      "alpha": 1,
      "hex": "#FFFFFF"
    },
  },
  "Color.Neutral.Black": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#000000"
    },
  },
  "Color.Neutral.SolidGray.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9490196108818054,
        0.9490196108818054,
        0.9490196108818054
      ],
      "alpha": 1,
      "hex": "#F2F2F2"
    },
  },
  "Color.Neutral.SolidGray.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9019607901573181,
        0.9019607901573181,
        0.9019607901573181
      ],
      "alpha": 1,
      "hex": "#E6E6E6"
    },
  },
  "Color.Neutral.SolidGray.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.800000011920929,
        0.800000011920929,
        0.800000011920929
      ],
      "alpha": 1,
      "hex": "#CCCCCC"
    },
  },
  "Color.Neutral.SolidGray.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7019608020782471,
        0.7019608020782471,
        0.7019608020782471
      ],
      "alpha": 1,
      "hex": "#B3B3B3"
    },
  },
  "Color.Neutral.SolidGray.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6000000238418579,
        0.6000000238418579,
        0.6000000238418579
      ],
      "alpha": 1,
      "hex": "#999999"
    },
  },
  "Color.Neutral.SolidGray.420": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5803921818733215,
        0.5803921818733215,
        0.5803921818733215
      ],
      "alpha": 1,
      "hex": "#949494"
    },
  },
  "Color.Neutral.SolidGray.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.49803921580314636,
        0.49803921580314636,
        0.49803921580314636
      ],
      "alpha": 1,
      "hex": "#7F7F7F"
    },
  },
  "Color.Neutral.SolidGray.536": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4628731310367584,
        0.4628731310367584,
        0.4628731310367584
      ],
      "alpha": 1,
      "hex": "#767676"
    },
  },
  "Color.Neutral.SolidGray.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4000000059604645,
        0.4000000059604645,
        0.4000000059604645
      ],
      "alpha": 1,
      "hex": "#666666"
    },
  },
  "Color.Neutral.SolidGray.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3019607961177826,
        0.3019607961177826,
        0.3019607961177826
      ],
      "alpha": 1,
      "hex": "#4D4D4D"
    },
  },
  "Color.Neutral.SolidGray.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.20000000298023224,
        0.20000000298023224,
        0.20000000298023224
      ],
      "alpha": 1,
      "hex": "#333333"
    },
  },
  "Color.Neutral.SolidGray.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.10196078568696976,
        0.10196078568696976,
        0.10196078568696976
      ],
      "alpha": 1,
      "hex": "#1A1A1A"
    },
  },
  "Color.Neutral.OpacityGray.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.05000000074505806,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.10000000149011612,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.20000000298023224,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.30000001192092896,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.4000000059604645,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.420": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.41999998688697815,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.5,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.536": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.5400000214576721,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.6000000238418579,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.699999988079071,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.800000011920929,
      "hex": "#000000"
    },
  },
  "Color.Neutral.OpacityGray.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.8999999761581421,
      "hex": "#000000"
    },
  },
  "Color.Primitive.Blue.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9098039269447327,
        0.9450980424880981,
        0.9960784316062927
      ],
      "alpha": 1,
      "hex": "#E8F1FE"
    },
  },
  "Color.Primitive.Blue.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8509804010391235,
        0.9019607901573181,
        1
      ],
      "alpha": 1,
      "hex": "#D9E6FF"
    },
  },
  "Color.Primitive.Blue.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.772549033164978,
        0.843137264251709,
        0.9843137264251709
      ],
      "alpha": 1,
      "hex": "#C5D7FB"
    },
  },
  "Color.Primitive.Blue.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.615686297416687,
        0.7176470756530762,
        0.9764705896377563
      ],
      "alpha": 1,
      "hex": "#9DB7F9"
    },
  },
  "Color.Primitive.Blue.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43921568989753723,
        0.5882353186607361,
        0.9725490212440491
      ],
      "alpha": 1,
      "hex": "#7096F8"
    },
  },
  "Color.Primitive.Blue.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2862745225429535,
        0.4745098054409027,
        0.9607843160629272
      ],
      "alpha": 1,
      "hex": "#4979F5"
    },
  },
  "Color.Primitive.Blue.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.20392157137393951,
        0.3764705955982208,
        0.9843137264251709
      ],
      "alpha": 1,
      "hex": "#3460FB"
    },
  },
  "Color.Primitive.Blue.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.14901961386203766,
        0.29019609093666077,
        0.95686274766922
      ],
      "alpha": 1,
      "hex": "#264AF4"
    },
  },
  "Color.Primitive.Blue.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.1921568661928177,
        0.8470588326454163
      ],
      "alpha": 1,
      "hex": "#0031D8"
    },
  },
  "Color.Primitive.Blue.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.09019608050584793,
        0.7568627595901489
      ],
      "alpha": 1,
      "hex": "#0017C1"
    },
  },
  "Color.Primitive.Blue.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.06666667014360428,
        0.5607843399047852
      ],
      "alpha": 1,
      "hex": "#00118F"
    },
  },
  "Color.Primitive.Blue.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0.4431372582912445
      ],
      "alpha": 1,
      "hex": "#000071"
    },
  },
  "Color.Primitive.Blue.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0.3764705955982208
      ],
      "alpha": 1,
      "hex": "#000060"
    },
  },
  "Color.Primitive.LightBlue.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9411764740943909,
        0.9764705896377563,
        1
      ],
      "alpha": 1,
      "hex": "#F0F9FF"
    },
  },
  "Color.Primitive.LightBlue.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8627451062202454,
        0.9411764740943909,
        1
      ],
      "alpha": 1,
      "hex": "#DCF0FF"
    },
  },
  "Color.Primitive.LightBlue.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411911964417,
        0.8941176533699036,
        1
      ],
      "alpha": 1,
      "hex": "#C0E4FF"
    },
  },
  "Color.Primitive.LightBlue.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5921568870544434,
        0.8274509906768799,
        1
      ],
      "alpha": 1,
      "hex": "#97D3FF"
    },
  },
  "Color.Primitive.LightBlue.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.34117648005485535,
        0.7215686440467834,
        1
      ],
      "alpha": 1,
      "hex": "#57B8FF"
    },
  },
  "Color.Primitive.LightBlue.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2235294133424759,
        0.6705882549285889,
        1
      ],
      "alpha": 1,
      "hex": "#39ABFF"
    },
  },
  "Color.Primitive.LightBlue.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.545098066329956,
        0.9490196108818054
      ],
      "alpha": 1,
      "hex": "#008BF2"
    },
  },
  "Color.Primitive.LightBlue.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.0313725508749485,
        0.46666666865348816,
        0.843137264251709
      ],
      "alpha": 1,
      "hex": "#0877D7"
    },
  },
  "Color.Primitive.LightBlue.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.4000000059604645,
        0.7450980544090271
      ],
      "alpha": 1,
      "hex": "#0066BE"
    },
  },
  "Color.Primitive.LightBlue.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.3333333432674408,
        0.6784313917160034
      ],
      "alpha": 1,
      "hex": "#0055AD"
    },
  },
  "Color.Primitive.LightBlue.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.25882354378700256,
        0.5490196347236633
      ],
      "alpha": 1,
      "hex": "#00428C"
    },
  },
  "Color.Primitive.LightBlue.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.1921568661928177,
        0.4156862795352936
      ],
      "alpha": 1,
      "hex": "#00316A"
    },
  },
  "Color.Primitive.LightBlue.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.13725490868091583,
        0.29411765933036804
      ],
      "alpha": 1,
      "hex": "#00234B"
    },
  },
  "Color.Primitive.Cyan.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9137254953384399,
        0.9686274528503418,
        0.9764705896377563
      ],
      "alpha": 1,
      "hex": "#E9F7F9"
    },
  },
  "Color.Primitive.Cyan.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7843137383460999,
        0.9725490212440491,
        1
      ],
      "alpha": 1,
      "hex": "#C8F8FF"
    },
  },
  "Color.Primitive.Cyan.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6000000238418579,
        0.9490196108818054,
        1
      ],
      "alpha": 1,
      "hex": "#99F2FF"
    },
  },
  "Color.Primitive.Cyan.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4745098054409027,
        0.886274516582489,
        0.9490196108818054
      ],
      "alpha": 1,
      "hex": "#79E2F2"
    },
  },
  "Color.Primitive.Cyan.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.16862745583057404,
        0.7843137383460999,
        0.8941176533699036
      ],
      "alpha": 1,
      "hex": "#2BC8E4"
    },
  },
  "Color.Primitive.Cyan.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.003921568859368563,
        0.7176470756530762,
        0.8392156958580017
      ],
      "alpha": 1,
      "hex": "#01B7D6"
    },
  },
  "Color.Primitive.Cyan.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.6392157077789307,
        0.7490196228027344
      ],
      "alpha": 1,
      "hex": "#00A3BF"
    },
  },
  "Color.Primitive.Cyan.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5529412031173706,
        0.6509804129600525
      ],
      "alpha": 1,
      "hex": "#008DA6"
    },
  },
  "Color.Primitive.Cyan.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5098039507865906,
        0.6000000238418579
      ],
      "alpha": 1,
      "hex": "#008299"
    },
  },
  "Color.Primitive.Cyan.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.43529412150382996,
        0.5137255191802979
      ],
      "alpha": 1,
      "hex": "#006F83"
    },
  },
  "Color.Primitive.Cyan.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.3803921639919281,
        0.45098039507865906
      ],
      "alpha": 1,
      "hex": "#006173"
    },
  },
  "Color.Primitive.Cyan.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.2980392277240753,
        0.3490196168422699
      ],
      "alpha": 1,
      "hex": "#004C59"
    },
  },
  "Color.Primitive.Cyan.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.21568627655506134,
        0.2549019753932953
      ],
      "alpha": 1,
      "hex": "#003741"
    },
  },
  "Color.Primitive.Green.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9019607901573181,
        0.9607843160629272,
        0.9254902005195618
      ],
      "alpha": 1,
      "hex": "#E6F5EC"
    },
  },
  "Color.Primitive.Green.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7607843279838562,
        0.8980392217636108,
        0.8196078538894653
      ],
      "alpha": 1,
      "hex": "#C2E5D1"
    },
  },
  "Color.Primitive.Green.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6078431606292725,
        0.8313725590705872,
        0.7098039388656616
      ],
      "alpha": 1,
      "hex": "#9BD4B5"
    },
  },
  "Color.Primitive.Green.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4431372582912445,
        0.772549033164978,
        0.5960784554481506
      ],
      "alpha": 1,
      "hex": "#71C598"
    },
  },
  "Color.Primitive.Green.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3176470696926117,
        0.7215686440467834,
        0.5137255191802979
      ],
      "alpha": 1,
      "hex": "#51B883"
    },
  },
  "Color.Primitive.Green.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.1725490242242813,
        0.6745098233222961,
        0.4313725531101227
      ],
      "alpha": 1,
      "hex": "#2CAC6E"
    },
  },
  "Color.Primitive.Green.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.14509804546833038,
        0.615686297416687,
        0.38823530077934265
      ],
      "alpha": 1,
      "hex": "#259D63"
    },
  },
  "Color.Primitive.Green.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.11372549086809158,
        0.545098066329956,
        0.33725491166114807
      ],
      "alpha": 1,
      "hex": "#1D8B56"
    },
  },
  "Color.Primitive.Green.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.09803921729326248,
        0.47843137383461,
        0.29411765933036804
      ],
      "alpha": 1,
      "hex": "#197A4B"
    },
  },
  "Color.Primitive.Green.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.06666667014360428,
        0.3529411852359772,
        0.21176470816135406
      ],
      "alpha": 1,
      "hex": "#115A36"
    },
  },
  "Color.Primitive.Green.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.0470588244497776,
        0.27843138575553894,
        0.16470588743686676
      ],
      "alpha": 1,
      "hex": "#0C472A"
    },
  },
  "Color.Primitive.Green.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.0313725508749485,
        0.2078431397676468,
        0.12156862765550613
      ],
      "alpha": 1,
      "hex": "#08351F"
    },
  },
  "Color.Primitive.Green.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.0117647061124444,
        0.13333334028720856,
        0.07450980693101883
      ],
      "alpha": 1,
      "hex": "#032213"
    },
  },
  "Color.Primitive.Lime.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9215686321258545,
        0.9803921580314636,
        0.8509804010391235
      ],
      "alpha": 1,
      "hex": "#EBFAD9"
    },
  },
  "Color.Primitive.Lime.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8156862854957581,
        0.9607843160629272,
        0.6352941393852234
      ],
      "alpha": 1,
      "hex": "#D0F5A2"
    },
  },
  "Color.Primitive.Lime.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411911964417,
        0.9529411792755127,
        0.3294117748737335
      ],
      "alpha": 1,
      "hex": "#C0F354"
    },
  },
  "Color.Primitive.Lime.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6784313917160034,
        0.9098039269447327,
        0.1882352977991104
      ],
      "alpha": 1,
      "hex": "#ADE830"
    },
  },
  "Color.Primitive.Lime.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.615686297416687,
        0.8666666746139526,
        0.08235294371843338
      ],
      "alpha": 1,
      "hex": "#9DDD15"
    },
  },
  "Color.Primitive.Lime.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5490196347236633,
        0.7843137383460999,
        0.0470588244497776
      ],
      "alpha": 1,
      "hex": "#8CC80C"
    },
  },
  "Color.Primitive.Lime.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4941176474094391,
        0.7058823704719543,
        0.05098039284348488
      ],
      "alpha": 1,
      "hex": "#7EB40D"
    },
  },
  "Color.Primitive.Lime.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43529412150382996,
        0.6313725709915161,
        0.01568627543747425
      ],
      "alpha": 1,
      "hex": "#6FA104"
    },
  },
  "Color.Primitive.Lime.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3803921639919281,
        0.5568627715110779,
        0
      ],
      "alpha": 1,
      "hex": "#618E00"
    },
  },
  "Color.Primitive.Lime.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137255012989044,
        0.4588235318660736,
        0
      ],
      "alpha": 1,
      "hex": "#507500"
    },
  },
  "Color.Primitive.Lime.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.24313725531101227,
        0.3529411852359772,
        0
      ],
      "alpha": 1,
      "hex": "#3E5A00"
    },
  },
  "Color.Primitive.Lime.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.1725490242242813,
        0.2549019753932953,
        0
      ],
      "alpha": 1,
      "hex": "#2C4100"
    },
  },
  "Color.Primitive.Lime.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.11764705926179886,
        0.1764705926179886,
        0
      ],
      "alpha": 1,
      "hex": "#1E2D00"
    },
  },
  "Color.Primitive.Yellow.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9843137264251709,
        0.9607843160629272,
        0.8784313797950745
      ],
      "alpha": 1,
      "hex": "#FBF5E0"
    },
  },
  "Color.Primitive.Yellow.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9411764740943909,
        0.7019608020782471
      ],
      "alpha": 1,
      "hex": "#FFF0B3"
    },
  },
  "Color.Primitive.Yellow.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8901960849761963,
        0.501960813999176
      ],
      "alpha": 1,
      "hex": "#FFE380"
    },
  },
  "Color.Primitive.Yellow.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8313725590705872,
        0.239215686917305
      ],
      "alpha": 1,
      "hex": "#FFD43D"
    },
  },
  "Color.Primitive.Yellow.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7803921699523926,
        0
      ],
      "alpha": 1,
      "hex": "#FFC700"
    },
  },
  "Color.Primitive.Yellow.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9215686321258545,
        0.7176470756530762,
        0
      ],
      "alpha": 1,
      "hex": "#EBB700"
    },
  },
  "Color.Primitive.Yellow.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8235294222831726,
        0.6431372761726379,
        0
      ],
      "alpha": 1,
      "hex": "#D2A400"
    },
  },
  "Color.Primitive.Yellow.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7176470756530762,
        0.5607843399047852,
        0
      ],
      "alpha": 1,
      "hex": "#B78F00"
    },
  },
  "Color.Primitive.Yellow.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6470588445663452,
        0.501960813999176,
        0
      ],
      "alpha": 1,
      "hex": "#A58000"
    },
  },
  "Color.Primitive.Yellow.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.572549045085907,
        0.4470588266849518,
        0
      ],
      "alpha": 1,
      "hex": "#927200"
    },
  },
  "Color.Primitive.Yellow.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.501960813999176,
        0.38823530077934265,
        0
      ],
      "alpha": 1,
      "hex": "#806300"
    },
  },
  "Color.Primitive.Yellow.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4313725531101227,
        0.33725491166114807,
        0
      ],
      "alpha": 1,
      "hex": "#6E5600"
    },
  },
  "Color.Primitive.Yellow.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3764705955982208,
        0.29411765933036804,
        0
      ],
      "alpha": 1,
      "hex": "#604B00"
    },
  },
  "Color.Primitive.Orange.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9333333373069763,
        0.886274516582489
      ],
      "alpha": 1,
      "hex": "#FFEEE2"
    },
  },
  "Color.Primitive.Orange.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8745098114013672,
        0.7921568751335144
      ],
      "alpha": 1,
      "hex": "#FFDFCA"
    },
  },
  "Color.Primitive.Orange.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7568627595901489,
        0.6000000238418579
      ],
      "alpha": 1,
      "hex": "#FFC199"
    },
  },
  "Color.Primitive.Orange.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6509804129600525,
        0.4274509847164154
      ],
      "alpha": 1,
      "hex": "#FFA66D"
    },
  },
  "Color.Primitive.Orange.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5529412031173706,
        0.2666666805744171
      ],
      "alpha": 1,
      "hex": "#FF8D44"
    },
  },
  "Color.Primitive.Orange.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.4627451002597809,
        0.1568627506494522
      ],
      "alpha": 1,
      "hex": "#FF7628"
    },
  },
  "Color.Primitive.Orange.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9843137264251709,
        0.35686275362968445,
        0.003921568859368563
      ],
      "alpha": 1,
      "hex": "#FB5B01"
    },
  },
  "Color.Primitive.Orange.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.886274516582489,
        0.3176470696926117,
        0
      ],
      "alpha": 1,
      "hex": "#E25100"
    },
  },
  "Color.Primitive.Orange.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7803921699523926,
        0.27843138575553894,
        0
      ],
      "alpha": 1,
      "hex": "#C74700"
    },
  },
  "Color.Primitive.Orange.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6745098233222961,
        0.24313725531101227,
        0
      ],
      "alpha": 1,
      "hex": "#AC3E00"
    },
  },
  "Color.Primitive.Orange.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.545098066329956,
        0.19607843458652496,
        0
      ],
      "alpha": 1,
      "hex": "#8B3200"
    },
  },
  "Color.Primitive.Orange.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4274509847164154,
        0.15294118225574493,
        0
      ],
      "alpha": 1,
      "hex": "#6D2700"
    },
  },
  "Color.Primitive.Orange.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3294117748737335,
        0.11764705926179886,
        0
      ],
      "alpha": 1,
      "hex": "#541E00"
    },
  },
  "Color.Primitive.Red.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9921568632125854,
        0.9333333373069763,
        0.9333333373069763
      ],
      "alpha": 1,
      "hex": "#FDEEEE"
    },
  },
  "Color.Primitive.Red.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8549019694328308,
        0.8549019694328308
      ],
      "alpha": 1,
      "hex": "#FFDADA"
    },
  },
  "Color.Primitive.Red.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7333333492279053,
        0.7333333492279053
      ],
      "alpha": 1,
      "hex": "#FFBBBB"
    },
  },
  "Color.Primitive.Red.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5882353186607361,
        0.5882353186607361
      ],
      "alpha": 1,
      "hex": "#FF9696"
    },
  },
  "Color.Primitive.Red.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.4431372582912445,
        0.4431372582912445
      ],
      "alpha": 1,
      "hex": "#FF7171"
    },
  },
  "Color.Primitive.Red.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.3294117748737335,
        0.3294117748737335
      ],
      "alpha": 1,
      "hex": "#FF5454"
    },
  },
  "Color.Primitive.Red.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9960784316062927,
        0.2235294133424759,
        0.2235294133424759
      ],
      "alpha": 1,
      "hex": "#FE3939"
    },
  },
  "Color.Primitive.Red.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9803921580314636,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#FA0000"
    },
  },
  "Color.Primitive.Red.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.925000011920929,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#EC0000"
    },
  },
  "Color.Primitive.Red.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8078431487083435,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#CE0000"
    },
  },
  "Color.Primitive.Red.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6627451181411743,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#A90000"
    },
  },
  "Color.Primitive.Red.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5215686559677124,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#850000"
    },
  },
  "Color.Primitive.Red.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3843137323856354,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#620000"
    },
  },
  "Color.Primitive.Magenta.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9529411792755127,
        0.8980392217636108,
        0.95686274766922
      ],
      "alpha": 1,
      "hex": "#F3E5F4"
    },
  },
  "Color.Primitive.Magenta.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8156862854957581,
        1
      ],
      "alpha": 1,
      "hex": "#FFD0FF"
    },
  },
  "Color.Primitive.Magenta.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6823529601097107,
        1
      ],
      "alpha": 1,
      "hex": "#FFAEFF"
    },
  },
  "Color.Primitive.Magenta.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5568627715110779,
        1
      ],
      "alpha": 1,
      "hex": "#FF8EFF"
    },
  },
  "Color.Primitive.Magenta.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9647058844566345,
        0.3803921639919281,
        0.9647058844566345
      ],
      "alpha": 1,
      "hex": "#F661F6"
    },
  },
  "Color.Primitive.Magenta.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9450980424880981,
        0.21568627655506134,
        0.9450980424880981
      ],
      "alpha": 1,
      "hex": "#F137F1"
    },
  },
  "Color.Primitive.Magenta.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8588235378265381,
        0,
        0.8588235378265381
      ],
      "alpha": 1,
      "hex": "#DB00DB"
    },
  },
  "Color.Primitive.Magenta.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411911964417,
        0,
        0.7529411911964417
      ],
      "alpha": 1,
      "hex": "#C000C0"
    },
  },
  "Color.Primitive.Magenta.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6666666865348816,
        0,
        0.6666666865348816
      ],
      "alpha": 1,
      "hex": "#AA00AA"
    },
  },
  "Color.Primitive.Magenta.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.545098066329956,
        0,
        0.545098066329956
      ],
      "alpha": 1,
      "hex": "#8B008B"
    },
  },
  "Color.Primitive.Magenta.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.42352941632270813,
        0,
        0.42352941632270813
      ],
      "alpha": 1,
      "hex": "#6C006C"
    },
  },
  "Color.Primitive.Magenta.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137255012989044,
        0,
        0.3137255012989044
      ],
      "alpha": 1,
      "hex": "#500050"
    },
  },
  "Color.Primitive.Magenta.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.23137255012989044,
        0,
        0.23137255012989044
      ],
      "alpha": 1,
      "hex": "#3B003B"
    },
  },
  "Color.Primitive.Purple.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9450980424880981,
        0.9176470637321472,
        0.9803921580314636
      ],
      "alpha": 1,
      "hex": "#F1EAFA"
    },
  },
  "Color.Primitive.Purple.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9254902005195618,
        0.8666666746139526,
        1
      ],
      "alpha": 1,
      "hex": "#ECDDFF"
    },
  },
  "Color.Primitive.Purple.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8666666746139526,
        0.7607843279838562,
        1
      ],
      "alpha": 1,
      "hex": "#DDC2FF"
    },
  },
  "Color.Primitive.Purple.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8039215803146362,
        0.6509804129600525,
        1
      ],
      "alpha": 1,
      "hex": "#CDA6FF"
    },
  },
  "Color.Primitive.Purple.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7333333492279053,
        0.529411792755127,
        1
      ],
      "alpha": 1,
      "hex": "#BB87FF"
    },
  },
  "Color.Primitive.Purple.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6470588445663452,
        0.3960784375667572,
        0.9725490212440491
      ],
      "alpha": 1,
      "hex": "#A565F8"
    },
  },
  "Color.Primitive.Purple.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5333333611488342,
        0.26274511218070984,
        0.8823529481887817
      ],
      "alpha": 1,
      "hex": "#8843E1"
    },
  },
  "Color.Primitive.Purple.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43529412150382996,
        0.13725490868091583,
        0.8156862854957581
      ],
      "alpha": 1,
      "hex": "#6F23D0"
    },
  },
  "Color.Primitive.Purple.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3607843220233917,
        0.062745101749897,
        0.7450980544090271
      ],
      "alpha": 1,
      "hex": "#5C10BE"
    },
  },
  "Color.Primitive.Purple.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3176470696926117,
        0.03529411926865578,
        0.6784313917160034
      ],
      "alpha": 1,
      "hex": "#5109AD"
    },
  },
  "Color.Primitive.Purple.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2549019753932953,
        0.01568627543747425,
        0.5568627715110779
      ],
      "alpha": 1,
      "hex": "#41048E"
    },
  },
  "Color.Primitive.Purple.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.1882352977991104,
        0.003921568859368563,
        0.42352941632270813
      ],
      "alpha": 1,
      "hex": "#30016C"
    },
  },
  "Color.Primitive.Purple.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.12941177189350128,
        0,
        0.29411765933036804
      ],
      "alpha": 1,
      "hex": "#21004B"
    },
  },
  "Color.Semantic.Success.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.14509804546833038,
        0.615686297416687,
        0.38823530077934265
      ],
      "alpha": 1,
      "hex": "#259D63"
    },
  },
  "Color.Semantic.Success.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.09803921729326248,
        0.47843137383461,
        0.29411765933036804
      ],
      "alpha": 1,
      "hex": "#197A4B"
    },
  },
  "Color.Semantic.Error.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.925000011920929,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#EC0000"
    },
  },
  "Color.Semantic.Error.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8078431487083435,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#CE0000"
    },
  },
  "Color.Semantic.Warning.Yellow.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7176470756530762,
        0.5607843399047852,
        0
      ],
      "alpha": 1,
      "hex": "#B78F00"
    },
  },
  "Color.Semantic.Warning.Yellow.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.572549045085907,
        0.4470588266849518,
        0
      ],
      "alpha": 1,
      "hex": "#927200"
    },
  },
  "Color.Semantic.Warning.Orange.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9843137264251709,
        0.35686275362968445,
        0.003921568859368563
      ],
      "alpha": 1,
      "hex": "#FB5B01"
    },
  },
  "Color.Semantic.Warning.Orange.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7803921699523926,
        0.27843138575553894,
        0
      ],
      "alpha": 1,
      "hex": "#C74700"
    },
  },
  "FontWeight.400": {
    ".": 400,
  },
  "FontWeight.700": {
    ".": 700,
  },
  "FontSize.14": {
    ".": 14,
  },
  "FontSize.16": {
    ".": 16,
  },
  "FontSize.17": {
    ".": 17,
  },
  "FontSize.18": {
    ".": 18,
  },
  "FontSize.20": {
    ".": 20,
  },
  "FontSize.22": {
    ".": 22,
  },
  "FontSize.24": {
    ".": 24,
  },
  "FontSize.26": {
    ".": 26,
  },
  "FontSize.28": {
    ".": 28,
  },
  "FontSize.32": {
    ".": 32,
  },
  "FontSize.36": {
    ".": 36,
  },
  "FontSize.45": {
    ".": 45,
  },
  "FontSize.48": {
    ".": 48,
  },
  "FontSize.57": {
    ".": 57,
  },
  "FontSize.64": {
    ".": 64,
  },
  "FontFamily.Sans": {
    ".": "Noto Sans JP",
  },
  "FontFamily.Mono": {
    ".": "Noto Sans Mono",
  },
  "BorderRadius.4": {
    ".": 4,
  },
  "BorderRadius.6": {
    ".": 6,
  },
  "BorderRadius.8": {
    ".": 8,
  },
  "BorderRadius.12": {
    ".": 12,
  },
  "BorderRadius.16": {
    ".": 16,
  },
  "BorderRadius.24": {
    ".": 24,
  },
  "BorderRadius.32": {
    ".": 32,
  },
  "BorderRadius.Full": {
    ".": 9999,
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
