/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "Color.Color.Primitive.Blue.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9098039215686274,
        0.9450980392156862,
        0.996078431372549
      ],
      "alpha": 1,
      "hex": "#e8f1fe"
    },
  },
  "Color.Color.Primitive.Blue.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8509803921568627,
        0.9019607843137255,
        1
      ],
      "alpha": 1,
      "hex": "#d9e6ff"
    },
  },
  "Color.Color.Primitive.Blue.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7725490196078432,
        0.8431372549019608,
        0.984313725490196
      ],
      "alpha": 1,
      "hex": "#c5d7fb"
    },
  },
  "Color.Color.Primitive.Blue.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.615686274509804,
        0.7176470588235294,
        0.9764705882352941
      ],
      "alpha": 1,
      "hex": "#9db7f9"
    },
  },
  "Color.Color.Primitive.Blue.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4392156862745098,
        0.5882352941176471,
        0.9725490196078431
      ],
      "alpha": 1,
      "hex": "#7096f8"
    },
  },
  "Color.Color.Primitive.Blue.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.28627450980392155,
        0.4745098039215686,
        0.9607843137254902
      ],
      "alpha": 1,
      "hex": "#4979f5"
    },
  },
  "Color.Color.Primitive.Blue.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.20392156862745098,
        0.3764705882352941,
        0.984313725490196
      ],
      "alpha": 1,
      "hex": "#3460fb"
    },
  },
  "Color.Color.Primitive.Blue.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.14901960784313725,
        0.2901960784313726,
        0.9568627450980393
      ],
      "alpha": 1,
      "hex": "#264af4"
    },
  },
  "Color.Color.Primitive.Blue.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.19215686274509805,
        0.8470588235294118
      ],
      "alpha": 1,
      "hex": "#0031d8"
    },
  },
  "Color.Color.Primitive.Blue.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.09019607843137255,
        0.7568627450980392
      ],
      "alpha": 1,
      "hex": "#0017c1"
    },
  },
  "Color.Color.Primitive.Blue.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.06666666666666667,
        0.5607843137254902
      ],
      "alpha": 1,
      "hex": "#00118f"
    },
  },
  "Color.Color.Primitive.Blue.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0.44313725490196076
      ],
      "alpha": 1,
      "hex": "#000071"
    },
  },
  "Color.Color.Primitive.Blue.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0.3764705882352941
      ],
      "alpha": 1,
      "hex": "#000060"
    },
  },
  "Color.Color.Primitive.LightBlue.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9411764705882353,
        0.9764705882352941,
        1
      ],
      "alpha": 1,
      "hex": "#f0f9ff"
    },
  },
  "Color.Color.Primitive.LightBlue.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8627450980392157,
        0.9411764705882353,
        1
      ],
      "alpha": 1,
      "hex": "#dcf0ff"
    },
  },
  "Color.Color.Primitive.LightBlue.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411764705882,
        0.8941176470588236,
        1
      ],
      "alpha": 1,
      "hex": "#c0e4ff"
    },
  },
  "Color.Color.Primitive.LightBlue.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.592156862745098,
        0.8274509803921568,
        1
      ],
      "alpha": 1,
      "hex": "#97d3ff"
    },
  },
  "Color.Color.Primitive.LightBlue.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3411764705882353,
        0.7215686274509804,
        1
      ],
      "alpha": 1,
      "hex": "#57b8ff"
    },
  },
  "Color.Color.Primitive.LightBlue.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2235294117647059,
        0.6705882352941176,
        1
      ],
      "alpha": 1,
      "hex": "#39abff"
    },
  },
  "Color.Color.Primitive.LightBlue.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5450980392156862,
        0.9490196078431372
      ],
      "alpha": 1,
      "hex": "#008bf2"
    },
  },
  "Color.Color.Primitive.LightBlue.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.03137254901960784,
        0.4666666666666667,
        0.8431372549019608
      ],
      "alpha": 1,
      "hex": "#0877d7"
    },
  },
  "Color.Color.Primitive.LightBlue.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.4,
        0.7450980392156863
      ],
      "alpha": 1,
      "hex": "#0066be"
    },
  },
  "Color.Color.Primitive.LightBlue.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.3333333333333333,
        0.6784313725490196
      ],
      "alpha": 1,
      "hex": "#0055ad"
    },
  },
  "Color.Color.Primitive.LightBlue.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.25882352941176473,
        0.5490196078431373
      ],
      "alpha": 1,
      "hex": "#00428c"
    },
  },
  "Color.Color.Primitive.LightBlue.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.19215686274509805,
        0.41568627450980394
      ],
      "alpha": 1,
      "hex": "#00316a"
    },
  },
  "Color.Color.Primitive.LightBlue.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.13725490196078433,
        0.29411764705882354
      ],
      "alpha": 1,
      "hex": "#00234b"
    },
  },
  "Color.Color.Primitive.Cyan.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9137254901960784,
        0.9686274509803922,
        0.9764705882352941
      ],
      "alpha": 1,
      "hex": "#e9f7f9"
    },
  },
  "Color.Color.Primitive.Cyan.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7843137254901961,
        0.9725490196078431,
        1
      ],
      "alpha": 1,
      "hex": "#c8f8ff"
    },
  },
  "Color.Color.Primitive.Cyan.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6,
        0.9490196078431372,
        1
      ],
      "alpha": 1,
      "hex": "#99f2ff"
    },
  },
  "Color.Color.Primitive.Cyan.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4745098039215686,
        0.8862745098039215,
        0.9490196078431372
      ],
      "alpha": 1,
      "hex": "#79e2f2"
    },
  },
  "Color.Color.Primitive.Cyan.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.16862745098039217,
        0.7843137254901961,
        0.8941176470588236
      ],
      "alpha": 1,
      "hex": "#2bc8e4"
    },
  },
  "Color.Color.Primitive.Cyan.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.00392156862745098,
        0.7176470588235294,
        0.8392156862745098
      ],
      "alpha": 1,
      "hex": "#01b7d6"
    },
  },
  "Color.Color.Primitive.Cyan.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.6392156862745098,
        0.7490196078431373
      ],
      "alpha": 1,
      "hex": "#00a3bf"
    },
  },
  "Color.Color.Primitive.Cyan.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5529411764705883,
        0.6509803921568628
      ],
      "alpha": 1,
      "hex": "#008da6"
    },
  },
  "Color.Color.Primitive.Cyan.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5098039215686274,
        0.6
      ],
      "alpha": 1,
      "hex": "#008299"
    },
  },
  "Color.Color.Primitive.Cyan.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.43529411764705883,
        0.5137254901960784
      ],
      "alpha": 1,
      "hex": "#006f83"
    },
  },
  "Color.Color.Primitive.Cyan.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.3803921568627451,
        0.45098039215686275
      ],
      "alpha": 1,
      "hex": "#006173"
    },
  },
  "Color.Color.Primitive.Cyan.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.2980392156862745,
        0.34901960784313724
      ],
      "alpha": 1,
      "hex": "#004c59"
    },
  },
  "Color.Color.Primitive.Cyan.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.21568627450980393,
        0.2549019607843137
      ],
      "alpha": 1,
      "hex": "#003741"
    },
  },
  "Color.Color.Primitive.Green.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9019607843137255,
        0.9607843137254902,
        0.9254901960784314
      ],
      "alpha": 1,
      "hex": "#e6f5ec"
    },
  },
  "Color.Color.Primitive.Green.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7607843137254902,
        0.8980392156862745,
        0.8196078431372549
      ],
      "alpha": 1,
      "hex": "#c2e5d1"
    },
  },
  "Color.Color.Primitive.Green.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6078431372549019,
        0.8313725490196079,
        0.7098039215686275
      ],
      "alpha": 1,
      "hex": "#9bd4b5"
    },
  },
  "Color.Color.Primitive.Green.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.44313725490196076,
        0.7725490196078432,
        0.596078431372549
      ],
      "alpha": 1,
      "hex": "#71c598"
    },
  },
  "Color.Color.Primitive.Green.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3176470588235294,
        0.7215686274509804,
        0.5137254901960784
      ],
      "alpha": 1,
      "hex": "#51b883"
    },
  },
  "Color.Color.Primitive.Green.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.17254901960784313,
        0.6745098039215687,
        0.43137254901960786
      ],
      "alpha": 1,
      "hex": "#2cac6e"
    },
  },
  "Color.Color.Primitive.Green.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.1450980392156863,
        0.615686274509804,
        0.38823529411764707
      ],
      "alpha": 1,
      "hex": "#259d63"
    },
  },
  "Color.Color.Primitive.Green.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.11372549019607843,
        0.5450980392156862,
        0.33725490196078434
      ],
      "alpha": 1,
      "hex": "#1d8b56"
    },
  },
  "Color.Color.Primitive.Green.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.09803921568627451,
        0.47843137254901963,
        0.29411764705882354
      ],
      "alpha": 1,
      "hex": "#197a4b"
    },
  },
  "Color.Color.Primitive.Green.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.06666666666666667,
        0.35294117647058826,
        0.21176470588235294
      ],
      "alpha": 1,
      "hex": "#115a36"
    },
  },
  "Color.Color.Primitive.Green.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.047058823529411764,
        0.2784313725490196,
        0.16470588235294117
      ],
      "alpha": 1,
      "hex": "#0c472a"
    },
  },
  "Color.Color.Primitive.Green.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.03137254901960784,
        0.20784313725490197,
        0.12156862745098039
      ],
      "alpha": 1,
      "hex": "#08351f"
    },
  },
  "Color.Color.Primitive.Green.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.011764705882352941,
        0.13333333333333333,
        0.07450980392156863
      ],
      "alpha": 1,
      "hex": "#032213"
    },
  },
  "Color.Color.Primitive.Lime.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9215686274509803,
        0.9803921568627451,
        0.8509803921568627
      ],
      "alpha": 1,
      "hex": "#ebfad9"
    },
  },
  "Color.Color.Primitive.Lime.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8156862745098039,
        0.9607843137254902,
        0.6352941176470588
      ],
      "alpha": 1,
      "hex": "#d0f5a2"
    },
  },
  "Color.Color.Primitive.Lime.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411764705882,
        0.9529411764705882,
        0.32941176470588235
      ],
      "alpha": 1,
      "hex": "#c0f354"
    },
  },
  "Color.Color.Primitive.Lime.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6784313725490196,
        0.9098039215686274,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#ade830"
    },
  },
  "Color.Color.Primitive.Lime.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.615686274509804,
        0.8666666666666667,
        0.08235294117647059
      ],
      "alpha": 1,
      "hex": "#9ddd15"
    },
  },
  "Color.Color.Primitive.Lime.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5490196078431373,
        0.7843137254901961,
        0.047058823529411764
      ],
      "alpha": 1,
      "hex": "#8cc80c"
    },
  },
  "Color.Color.Primitive.Lime.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.49411764705882355,
        0.7058823529411765,
        0.050980392156862744
      ],
      "alpha": 1,
      "hex": "#7eb40d"
    },
  },
  "Color.Color.Primitive.Lime.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43529411764705883,
        0.6313725490196078,
        0.01568627450980392
      ],
      "alpha": 1,
      "hex": "#6fa104"
    },
  },
  "Color.Color.Primitive.Lime.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3803921568627451,
        0.5568627450980392,
        0
      ],
      "alpha": 1,
      "hex": "#618e00"
    },
  },
  "Color.Color.Primitive.Lime.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137254901960784,
        0.4588235294117647,
        0
      ],
      "alpha": 1,
      "hex": "#507500"
    },
  },
  "Color.Color.Primitive.Lime.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.24313725490196078,
        0.35294117647058826,
        0
      ],
      "alpha": 1,
      "hex": "#3e5a00"
    },
  },
  "Color.Color.Primitive.Lime.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.17254901960784313,
        0.2549019607843137,
        0
      ],
      "alpha": 1,
      "hex": "#2c4100"
    },
  },
  "Color.Color.Primitive.Lime.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.11764705882352941,
        0.17647058823529413,
        0
      ],
      "alpha": 1,
      "hex": "#1e2d00"
    },
  },
  "Color.Color.Primitive.Yellow.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.984313725490196,
        0.9607843137254902,
        0.8784313725490196
      ],
      "alpha": 1,
      "hex": "#fbf5e0"
    },
  },
  "Color.Color.Primitive.Yellow.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9411764705882353,
        0.7019607843137254
      ],
      "alpha": 1,
      "hex": "#fff0b3"
    },
  },
  "Color.Color.Primitive.Yellow.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8901960784313725,
        0.5019607843137255
      ],
      "alpha": 1,
      "hex": "#ffe380"
    },
  },
  "Color.Color.Primitive.Yellow.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8313725490196079,
        0.23921568627450981
      ],
      "alpha": 1,
      "hex": "#ffd43d"
    },
  },
  "Color.Color.Primitive.Yellow.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7803921568627451,
        0
      ],
      "alpha": 1,
      "hex": "#ffc700"
    },
  },
  "Color.Color.Primitive.Yellow.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9215686274509803,
        0.7176470588235294,
        0
      ],
      "alpha": 1,
      "hex": "#ebb700"
    },
  },
  "Color.Color.Primitive.Yellow.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8235294117647058,
        0.6431372549019608,
        0
      ],
      "alpha": 1,
      "hex": "#d2a400"
    },
  },
  "Color.Color.Primitive.Yellow.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7176470588235294,
        0.5607843137254902,
        0
      ],
      "alpha": 1,
      "hex": "#b78f00"
    },
  },
  "Color.Color.Primitive.Yellow.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6470588235294118,
        0.5019607843137255,
        0
      ],
      "alpha": 1,
      "hex": "#a58000"
    },
  },
  "Color.Color.Primitive.Yellow.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5725490196078431,
        0.4470588235294118,
        0
      ],
      "alpha": 1,
      "hex": "#927200"
    },
  },
  "Color.Color.Primitive.Yellow.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5019607843137255,
        0.38823529411764707,
        0
      ],
      "alpha": 1,
      "hex": "#806300"
    },
  },
  "Color.Color.Primitive.Yellow.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43137254901960786,
        0.33725490196078434,
        0
      ],
      "alpha": 1,
      "hex": "#6e5600"
    },
  },
  "Color.Color.Primitive.Yellow.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3764705882352941,
        0.29411764705882354,
        0
      ],
      "alpha": 1,
      "hex": "#604b00"
    },
  },
  "Color.Color.Primitive.Orange.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9333333333333333,
        0.8862745098039215
      ],
      "alpha": 1,
      "hex": "#ffeee2"
    },
  },
  "Color.Color.Primitive.Orange.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8745098039215686,
        0.792156862745098
      ],
      "alpha": 1,
      "hex": "#ffdfca"
    },
  },
  "Color.Color.Primitive.Orange.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7568627450980392,
        0.6
      ],
      "alpha": 1,
      "hex": "#ffc199"
    },
  },
  "Color.Color.Primitive.Orange.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6509803921568628,
        0.42745098039215684
      ],
      "alpha": 1,
      "hex": "#ffa66d"
    },
  },
  "Color.Color.Primitive.Orange.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5529411764705883,
        0.26666666666666666
      ],
      "alpha": 1,
      "hex": "#ff8d44"
    },
  },
  "Color.Color.Primitive.Orange.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.4627450980392157,
        0.1568627450980392
      ],
      "alpha": 1,
      "hex": "#ff7628"
    },
  },
  "Color.Color.Primitive.Orange.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.984313725490196,
        0.3568627450980392,
        0.00392156862745098
      ],
      "alpha": 1,
      "hex": "#fb5b01"
    },
  },
  "Color.Color.Primitive.Orange.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8862745098039215,
        0.3176470588235294,
        0
      ],
      "alpha": 1,
      "hex": "#e25100"
    },
  },
  "Color.Color.Primitive.Orange.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7803921568627451,
        0.2784313725490196,
        0
      ],
      "alpha": 1,
      "hex": "#c74700"
    },
  },
  "Color.Color.Primitive.Orange.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6745098039215687,
        0.24313725490196078,
        0
      ],
      "alpha": 1,
      "hex": "#ac3e00"
    },
  },
  "Color.Color.Primitive.Orange.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5450980392156862,
        0.19607843137254902,
        0
      ],
      "alpha": 1,
      "hex": "#8b3200"
    },
  },
  "Color.Color.Primitive.Orange.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.42745098039215684,
        0.15294117647058825,
        0
      ],
      "alpha": 1,
      "hex": "#6d2700"
    },
  },
  "Color.Color.Primitive.Orange.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.32941176470588235,
        0.11764705882352941,
        0
      ],
      "alpha": 1,
      "hex": "#541e00"
    },
  },
  "Color.Color.Primitive.Red.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9921568627450981,
        0.9333333333333333,
        0.9333333333333333
      ],
      "alpha": 1,
      "hex": "#fdeeee"
    },
  },
  "Color.Color.Primitive.Red.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8549019607843137,
        0.8549019607843137
      ],
      "alpha": 1,
      "hex": "#ffdada"
    },
  },
  "Color.Color.Primitive.Red.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7333333333333333,
        0.7333333333333333
      ],
      "alpha": 1,
      "hex": "#ffbbbb"
    },
  },
  "Color.Color.Primitive.Red.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5882352941176471,
        0.5882352941176471
      ],
      "alpha": 1,
      "hex": "#ff9696"
    },
  },
  "Color.Color.Primitive.Red.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.44313725490196076,
        0.44313725490196076
      ],
      "alpha": 1,
      "hex": "#ff7171"
    },
  },
  "Color.Color.Primitive.Red.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.32941176470588235,
        0.32941176470588235
      ],
      "alpha": 1,
      "hex": "#ff5454"
    },
  },
  "Color.Color.Primitive.Red.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.996078431372549,
        0.2235294117647059,
        0.2235294117647059
      ],
      "alpha": 1,
      "hex": "#fe3939"
    },
  },
  "Color.Color.Primitive.Red.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9803921568627451,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#fa0000"
    },
  },
  "Color.Color.Primitive.Red.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9254901960784314,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#ec0000"
    },
  },
  "Color.Color.Primitive.Red.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.807843137254902,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#ce0000"
    },
  },
  "Color.Color.Primitive.Red.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6627450980392157,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#a90000"
    },
  },
  "Color.Color.Primitive.Red.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5215686274509804,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#850000"
    },
  },
  "Color.Color.Primitive.Red.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3843137254901961,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#620000"
    },
  },
  "Color.Color.Primitive.Magenta.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9529411764705882,
        0.8980392156862745,
        0.9568627450980393
      ],
      "alpha": 1,
      "hex": "#f3e5f4"
    },
  },
  "Color.Color.Primitive.Magenta.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8156862745098039,
        1
      ],
      "alpha": 1,
      "hex": "#ffd0ff"
    },
  },
  "Color.Color.Primitive.Magenta.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6823529411764706,
        1
      ],
      "alpha": 1,
      "hex": "#ffaeff"
    },
  },
  "Color.Color.Primitive.Magenta.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5568627450980392,
        1
      ],
      "alpha": 1,
      "hex": "#ff8eff"
    },
  },
  "Color.Color.Primitive.Magenta.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9647058823529412,
        0.3803921568627451,
        0.9647058823529412
      ],
      "alpha": 1,
      "hex": "#f661f6"
    },
  },
  "Color.Color.Primitive.Magenta.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9450980392156862,
        0.21568627450980393,
        0.9450980392156862
      ],
      "alpha": 1,
      "hex": "#f137f1"
    },
  },
  "Color.Color.Primitive.Magenta.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8588235294117647,
        0,
        0.8588235294117647
      ],
      "alpha": 1,
      "hex": "#db00db"
    },
  },
  "Color.Color.Primitive.Magenta.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411764705882,
        0,
        0.7529411764705882
      ],
      "alpha": 1,
      "hex": "#c000c0"
    },
  },
  "Color.Color.Primitive.Magenta.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6666666666666666,
        0,
        0.6666666666666666
      ],
      "alpha": 1,
      "hex": "#aa00aa"
    },
  },
  "Color.Color.Primitive.Magenta.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5450980392156862,
        0,
        0.5450980392156862
      ],
      "alpha": 1,
      "hex": "#8b008b"
    },
  },
  "Color.Color.Primitive.Magenta.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4235294117647059,
        0,
        0.4235294117647059
      ],
      "alpha": 1,
      "hex": "#6c006c"
    },
  },
  "Color.Color.Primitive.Magenta.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137254901960784,
        0,
        0.3137254901960784
      ],
      "alpha": 1,
      "hex": "#500050"
    },
  },
  "Color.Color.Primitive.Magenta.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.23137254901960785,
        0,
        0.23137254901960785
      ],
      "alpha": 1,
      "hex": "#3b003b"
    },
  },
  "Color.Color.Primitive.Purple.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9450980392156862,
        0.9176470588235294,
        0.9803921568627451
      ],
      "alpha": 1,
      "hex": "#f1eafa"
    },
  },
  "Color.Color.Primitive.Purple.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9254901960784314,
        0.8666666666666667,
        1
      ],
      "alpha": 1,
      "hex": "#ecddff"
    },
  },
  "Color.Color.Primitive.Purple.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8666666666666667,
        0.7607843137254902,
        1
      ],
      "alpha": 1,
      "hex": "#ddc2ff"
    },
  },
  "Color.Color.Primitive.Purple.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.803921568627451,
        0.6509803921568628,
        1
      ],
      "alpha": 1,
      "hex": "#cda6ff"
    },
  },
  "Color.Color.Primitive.Purple.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7333333333333333,
        0.5294117647058824,
        1
      ],
      "alpha": 1,
      "hex": "#bb87ff"
    },
  },
  "Color.Color.Primitive.Purple.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6470588235294118,
        0.396078431372549,
        0.9725490196078431
      ],
      "alpha": 1,
      "hex": "#a565f8"
    },
  },
  "Color.Color.Primitive.Purple.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5333333333333333,
        0.2627450980392157,
        0.8823529411764706
      ],
      "alpha": 1,
      "hex": "#8843e1"
    },
  },
  "Color.Color.Primitive.Purple.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.43529411764705883,
        0.13725490196078433,
        0.8156862745098039
      ],
      "alpha": 1,
      "hex": "#6f23d0"
    },
  },
  "Color.Color.Primitive.Purple.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3607843137254902,
        0.06274509803921569,
        0.7450980392156863
      ],
      "alpha": 1,
      "hex": "#5c10be"
    },
  },
  "Color.Color.Primitive.Purple.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3176470588235294,
        0.03529411764705882,
        0.6784313725490196
      ],
      "alpha": 1,
      "hex": "#5109ad"
    },
  },
  "Color.Color.Primitive.Purple.1000": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2549019607843137,
        0.01568627450980392,
        0.5568627450980392
      ],
      "alpha": 1,
      "hex": "#41048e"
    },
  },
  "Color.Color.Primitive.Purple.1100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.18823529411764706,
        0.00392156862745098,
        0.4235294117647059
      ],
      "alpha": 1,
      "hex": "#30016c"
    },
  },
  "Color.Color.Primitive.Purple.1200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.12941176470588237,
        0,
        0.29411764705882354
      ],
      "alpha": 1,
      "hex": "#21004b"
    },
  },
  "Color.Color.Neutral.White": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        1,
        1
      ],
      "alpha": 1,
      "hex": "#ffffff"
    },
  },
  "Color.Color.Neutral.Black": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.SolidGray.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9490196078431372,
        0.9490196078431372,
        0.9490196078431372
      ],
      "alpha": 1,
      "hex": "#f2f2f2"
    },
  },
  "Color.Color.Neutral.SolidGray.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9019607843137255,
        0.9019607843137255,
        0.9019607843137255
      ],
      "alpha": 1,
      "hex": "#e6e6e6"
    },
  },
  "Color.Color.Neutral.SolidGray.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8,
        0.8,
        0.8
      ],
      "alpha": 1,
      "hex": "#cccccc"
    },
  },
  "Color.Color.Neutral.SolidGray.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7019607843137254,
        0.7019607843137254,
        0.7019607843137254
      ],
      "alpha": 1,
      "hex": "#b3b3b3"
    },
  },
  "Color.Color.Neutral.SolidGray.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6,
        0.6,
        0.6
      ],
      "alpha": 1,
      "hex": "#999999"
    },
  },
  "Color.Color.Neutral.SolidGray.420": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5803921568627451,
        0.5803921568627451,
        0.5803921568627451
      ],
      "alpha": 1,
      "hex": "#949494"
    },
  },
  "Color.Color.Neutral.SolidGray.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4980392156862745,
        0.4980392156862745,
        0.4980392156862745
      ],
      "alpha": 1,
      "hex": "#7f7f7f"
    },
  },
  "Color.Color.Neutral.SolidGray.536": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4627450980392157,
        0.4627450980392157,
        0.4627450980392157
      ],
      "alpha": 1,
      "hex": "#767676"
    },
  },
  "Color.Color.Neutral.SolidGray.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4,
        0.4,
        0.4
      ],
      "alpha": 1,
      "hex": "#666666"
    },
  },
  "Color.Color.Neutral.SolidGray.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.30196078431372547,
        0.30196078431372547,
        0.30196078431372547
      ],
      "alpha": 1,
      "hex": "#4d4d4d"
    },
  },
  "Color.Color.Neutral.SolidGray.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2,
        0.2,
        0.2
      ],
      "alpha": 1,
      "hex": "#333333"
    },
  },
  "Color.Color.Neutral.SolidGray.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.10196078431372549,
        0.10196078431372549,
        0.10196078431372549
      ],
      "alpha": 1,
      "hex": "#1a1a1a"
    },
  },
  "Color.Color.Neutral.OpacityGray.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.050980392156862744,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.10196078431372549,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.2,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.30196078431372547,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.4,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.420": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.4196078431372549,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.5019607843137255,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.536": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.5411764705882353,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.6,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.7019607843137254,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.8,
      "hex": "#000000"
    },
  },
  "Color.Color.Neutral.OpacityGray.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 0.9019607843137255,
      "hex": "#000000"
    },
  },
  "Color.Color.Semantic.Success.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.1450980392156863,
        0.615686274509804,
        0.38823529411764707
      ],
      "alpha": 1,
      "hex": "#259d63"
    },
  },
  "Color.Color.Semantic.Success.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.09803921568627451,
        0.47843137254901963,
        0.29411764705882354
      ],
      "alpha": 1,
      "hex": "#197a4b"
    },
  },
  "Color.Color.Semantic.Error.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9254901960784314,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#ec0000"
    },
  },
  "Color.Color.Semantic.Error.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.807843137254902,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#ce0000"
    },
  },
  "Color.Color.Semantic.Warning.Yellow.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7176470588235294,
        0.5607843137254902,
        0
      ],
      "alpha": 1,
      "hex": "#b78f00"
    },
  },
  "Color.Color.Semantic.Warning.Yellow.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5725490196078431,
        0.4470588235294118,
        0
      ],
      "alpha": 1,
      "hex": "#927200"
    },
  },
  "Color.Color.Semantic.Warning.Orange.1": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.984313725490196,
        0.3568627450980392,
        0.00392156862745098
      ],
      "alpha": 1,
      "hex": "#fb5b01"
    },
  },
  "Color.Color.Semantic.Warning.Orange.2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7803921568627451,
        0.2784313725490196,
        0
      ],
      "alpha": 1,
      "hex": "#c74700"
    },
  },
  "Typography.FontWeight.400": {
    ".": "400",
  },
  "Typography.FontWeight.700": {
    ".": "700",
  },
  "Typography.FontSize.14": {
    ".": {
      "value": 14,
      "unit": "px"
    },
  },
  "Typography.FontSize.16": {
    ".": {
      "value": 16,
      "unit": "px"
    },
  },
  "Typography.FontSize.17": {
    ".": {
      "value": 17,
      "unit": "px"
    },
  },
  "Typography.FontSize.18": {
    ".": {
      "value": 18,
      "unit": "px"
    },
  },
  "Typography.FontSize.20": {
    ".": {
      "value": 20,
      "unit": "px"
    },
  },
  "Typography.FontSize.22": {
    ".": {
      "value": 22,
      "unit": "px"
    },
  },
  "Typography.FontSize.24": {
    ".": {
      "value": 24,
      "unit": "px"
    },
  },
  "Typography.FontSize.26": {
    ".": {
      "value": 26,
      "unit": "px"
    },
  },
  "Typography.FontSize.28": {
    ".": {
      "value": 28,
      "unit": "px"
    },
  },
  "Typography.FontSize.32": {
    ".": {
      "value": 32,
      "unit": "px"
    },
  },
  "Typography.FontSize.36": {
    ".": {
      "value": 36,
      "unit": "px"
    },
  },
  "Typography.FontSize.45": {
    ".": {
      "value": 45,
      "unit": "px"
    },
  },
  "Typography.FontSize.48": {
    ".": {
      "value": 48,
      "unit": "px"
    },
  },
  "Typography.FontSize.57": {
    ".": {
      "value": 57,
      "unit": "px"
    },
  },
  "Typography.FontSize.64": {
    ".": {
      "value": 64,
      "unit": "px"
    },
  },
  "Typography.FontFamily.Sans": {
    ".": "Noto Sans JP",
  },
  "Typography.FontFamily.Mono": {
    ".": "Noto Sans Mono",
  },
  "Size.BorderRadius.4": {
    ".": {
      "value": 4,
      "unit": "px"
    },
  },
  "Size.BorderRadius.6": {
    ".": {
      "value": 6,
      "unit": "px"
    },
  },
  "Size.BorderRadius.8": {
    ".": {
      "value": 8,
      "unit": "px"
    },
  },
  "Size.BorderRadius.12": {
    ".": {
      "value": 12,
      "unit": "px"
    },
  },
  "Size.BorderRadius.16": {
    ".": {
      "value": 16,
      "unit": "px"
    },
  },
  "Size.BorderRadius.24": {
    ".": {
      "value": 24,
      "unit": "px"
    },
  },
  "Size.BorderRadius.32": {
    ".": {
      "value": 32,
      "unit": "px"
    },
  },
  "Size.BorderRadius.Full": {
    ".": {
      "value": 9999,
      "unit": "px"
    },
  },
  "Effect-styles.Elevation.1": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 1,
          "unit": "px"
        },
        "blur": {
          "value": 5,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 2,
          "unit": "px"
        },
        "blur": {
          "value": 8,
          "unit": "px"
        },
        "spread": {
          "value": 1,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.2": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 1,
          "unit": "px"
        },
        "blur": {
          "value": 6,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 2,
          "unit": "px"
        },
        "blur": {
          "value": 12,
          "unit": "px"
        },
        "spread": {
          "value": 2,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.3": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 1,
          "unit": "px"
        },
        "blur": {
          "value": 6,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 4,
          "unit": "px"
        },
        "blur": {
          "value": 16,
          "unit": "px"
        },
        "spread": {
          "value": 3,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.4": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 2,
          "unit": "px"
        },
        "blur": {
          "value": 6,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 6,
          "unit": "px"
        },
        "blur": {
          "value": 20,
          "unit": "px"
        },
        "spread": {
          "value": 4,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.5": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 2,
          "unit": "px"
        },
        "blur": {
          "value": 10,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 8,
          "unit": "px"
        },
        "blur": {
          "value": 24,
          "unit": "px"
        },
        "spread": {
          "value": 5,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.6": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 3,
          "unit": "px"
        },
        "blur": {
          "value": 12,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 10,
          "unit": "px"
        },
        "blur": {
          "value": 30,
          "unit": "px"
        },
        "spread": {
          "value": 6,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.7": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 3,
          "unit": "px"
        },
        "blur": {
          "value": 14,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 12,
          "unit": "px"
        },
        "blur": {
          "value": 36,
          "unit": "px"
        },
        "spread": {
          "value": 7,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
  "Effect-styles.Elevation.8": {
    ".": [
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.30196078431372547,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 3,
          "unit": "px"
        },
        "blur": {
          "value": 16,
          "unit": "px"
        },
        "spread": {
          "value": 0,
          "unit": "px"
        },
        "inset": false
      },
      {
        "color": {
          "colorSpace": "srgb",
          "components": [
            0,
            0,
            0
          ],
          "alpha": 0.10196078431372549,
          "hex": "#000000"
        },
        "offsetX": {
          "value": 0,
          "unit": "px"
        },
        "offsetY": {
          "value": 14,
          "unit": "px"
        },
        "blur": {
          "value": 40,
          "unit": "px"
        },
        "spread": {
          "value": 7,
          "unit": "px"
        },
        "inset": false
      }
    ],
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
